export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENT = "SET_INGREDIENT";
export const SET_INGREDIENT_FAILED = "SET_INGREDIENT_FAILED";

export const SET_ORDER_SUCCESS = "SET_ORDER_SUCCESS";
export const SET_ORDER_FAILED = "SET_ORDER_FAILED";
export const SET_ORDERS_SUCCESS = "SET_ORDERS_SUCCESS";
export const SET_ORDERS_FAILED = "SET_ORDERS_FAILED";
